package com.snoweagle.console.dal.domain;

import java.math.BigDecimal;

public class ControlOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.fund_channel_code
     *
     * @mbggenerated
     */
    private String fundChannelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.source_code
     *
     * @mbggenerated
     */
    private String sourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.request_no
     *
     * @mbggenerated
     */
    private String requestNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.request_type
     *
     * @mbggenerated
     */
    private String requestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.api_type
     *
     * @mbggenerated
     */
    private String apiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.inst_order_no
     *
     * @mbggenerated
     */
    private String instOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.pre_request_no
     *
     * @mbggenerated
     */
    private String preRequestNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.communicate_status
     *
     * @mbggenerated
     */
    private String communicateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.retry_status
     *
     * @mbggenerated
     */
    private String retryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.notify_status
     *
     * @mbggenerated
     */
    private String notifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.gmt_create
     *
     * @mbggenerated
     */
    private String gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.gmt_modified
     *
     * @mbggenerated
     */
    private String gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.extension
     *
     * @mbggenerated
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_control_order.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.order_id
     *
     * @return the value of tt_control_order.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.order_id
     *
     * @param orderId the value for tt_control_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.fund_channel_code
     *
     * @return the value of tt_control_order.fund_channel_code
     *
     * @mbggenerated
     */
    public String getFundChannelCode() {
        return fundChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.fund_channel_code
     *
     * @param fundChannelCode the value for tt_control_order.fund_channel_code
     *
     * @mbggenerated
     */
    public void setFundChannelCode(String fundChannelCode) {
        this.fundChannelCode = fundChannelCode == null ? null : fundChannelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.source_code
     *
     * @return the value of tt_control_order.source_code
     *
     * @mbggenerated
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.source_code
     *
     * @param sourceCode the value for tt_control_order.source_code
     *
     * @mbggenerated
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.request_no
     *
     * @return the value of tt_control_order.request_no
     *
     * @mbggenerated
     */
    public String getRequestNo() {
        return requestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.request_no
     *
     * @param requestNo the value for tt_control_order.request_no
     *
     * @mbggenerated
     */
    public void setRequestNo(String requestNo) {
        this.requestNo = requestNo == null ? null : requestNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.request_type
     *
     * @return the value of tt_control_order.request_type
     *
     * @mbggenerated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.request_type
     *
     * @param requestType the value for tt_control_order.request_type
     *
     * @mbggenerated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.api_type
     *
     * @return the value of tt_control_order.api_type
     *
     * @mbggenerated
     */
    public String getApiType() {
        return apiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.api_type
     *
     * @param apiType the value for tt_control_order.api_type
     *
     * @mbggenerated
     */
    public void setApiType(String apiType) {
        this.apiType = apiType == null ? null : apiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.inst_order_no
     *
     * @return the value of tt_control_order.inst_order_no
     *
     * @mbggenerated
     */
    public String getInstOrderNo() {
        return instOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.inst_order_no
     *
     * @param instOrderNo the value for tt_control_order.inst_order_no
     *
     * @mbggenerated
     */
    public void setInstOrderNo(String instOrderNo) {
        this.instOrderNo = instOrderNo == null ? null : instOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.pre_request_no
     *
     * @return the value of tt_control_order.pre_request_no
     *
     * @mbggenerated
     */
    public String getPreRequestNo() {
        return preRequestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.pre_request_no
     *
     * @param preRequestNo the value for tt_control_order.pre_request_no
     *
     * @mbggenerated
     */
    public void setPreRequestNo(String preRequestNo) {
        this.preRequestNo = preRequestNo == null ? null : preRequestNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.amount
     *
     * @return the value of tt_control_order.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.amount
     *
     * @param amount the value for tt_control_order.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.status
     *
     * @return the value of tt_control_order.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.status
     *
     * @param status the value for tt_control_order.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.flag
     *
     * @return the value of tt_control_order.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.flag
     *
     * @param flag the value for tt_control_order.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.communicate_status
     *
     * @return the value of tt_control_order.communicate_status
     *
     * @mbggenerated
     */
    public String getCommunicateStatus() {
        return communicateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.communicate_status
     *
     * @param communicateStatus the value for tt_control_order.communicate_status
     *
     * @mbggenerated
     */
    public void setCommunicateStatus(String communicateStatus) {
        this.communicateStatus = communicateStatus == null ? null : communicateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.retry_status
     *
     * @return the value of tt_control_order.retry_status
     *
     * @mbggenerated
     */
    public String getRetryStatus() {
        return retryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.retry_status
     *
     * @param retryStatus the value for tt_control_order.retry_status
     *
     * @mbggenerated
     */
    public void setRetryStatus(String retryStatus) {
        this.retryStatus = retryStatus == null ? null : retryStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.notify_status
     *
     * @return the value of tt_control_order.notify_status
     *
     * @mbggenerated
     */
    public String getNotifyStatus() {
        return notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.notify_status
     *
     * @param notifyStatus the value for tt_control_order.notify_status
     *
     * @mbggenerated
     */
    public void setNotifyStatus(String notifyStatus) {
        this.notifyStatus = notifyStatus == null ? null : notifyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.gmt_create
     *
     * @return the value of tt_control_order.gmt_create
     *
     * @mbggenerated
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.gmt_create
     *
     * @param gmtCreate the value for tt_control_order.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.gmt_modified
     *
     * @return the value of tt_control_order.gmt_modified
     *
     * @mbggenerated
     */
    public String getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.gmt_modified
     *
     * @param gmtModified the value for tt_control_order.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(String gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.extension
     *
     * @return the value of tt_control_order.extension
     *
     * @mbggenerated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.extension
     *
     * @param extension the value for tt_control_order.extension
     *
     * @mbggenerated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_control_order.memo
     *
     * @return the value of tt_control_order.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_control_order.memo
     *
     * @param memo the value for tt_control_order.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}