package com.snoweagle.console.dal.domain;

import java.math.BigDecimal;
import java.util.Date;

public class InstOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.inst_order_id
     *
     * @mbggenerated
     */
    private Long instOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.inst_order_no
     *
     * @mbggenerated
     */
    private String instOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.request_type
     *
     * @mbggenerated
     */
    private String requestType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.fund_channel_code
     *
     * @mbggenerated
     */
    private String fundChannelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.fund_channel_api
     *
     * @mbggenerated
     */
    private String fundChannelApi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.communicate_type
     *
     * @mbggenerated
     */
    private String communicateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.communicate_status
     *
     * @mbggenerated
     */
    private String communicateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.gmt_submit
     *
     * @mbggenerated
     */
    private Date gmtSubmit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.retry_times
     *
     * @mbggenerated
     */
    private Integer retryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.gmt_next_retry
     *
     * @mbggenerated
     */
    private String gmtNextRetry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.gmt_create
     *
     * @mbggenerated
     */
    private String gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.gmt_modified
     *
     * @mbggenerated
     */
    private String gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.memo
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.extension
     *
     * @mbggenerated
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.portion
     *
     * @mbggenerated
     */
    private BigDecimal portion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.product_code
     *
     * @mbggenerated
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.gmt_booking_submit
     *
     * @mbggenerated
     */
    private Date gmtBookingSubmit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.payment_seq_no
     *
     * @mbggenerated
     */
    private String paymentSeqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.inst_user_no
     *
     * @mbggenerated
     */
    private String instUserNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.biz_time
     *
     * @mbggenerated
     */
    private Date bizTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.channel_date
     *
     * @mbggenerated
     */
    private Date channelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.biz_type
     *
     * @mbggenerated
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.fund_date
     *
     * @mbggenerated
     */
    private Date fundDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_inst_order.pre_inst_order_no
     *
     * @mbggenerated
     */
    private String preInstOrderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.inst_order_id
     *
     * @return the value of tt_inst_order.inst_order_id
     *
     * @mbggenerated
     */
    public Long getInstOrderId() {
        return instOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.inst_order_id
     *
     * @param instOrderId the value for tt_inst_order.inst_order_id
     *
     * @mbggenerated
     */
    public void setInstOrderId(Long instOrderId) {
        this.instOrderId = instOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.inst_order_no
     *
     * @return the value of tt_inst_order.inst_order_no
     *
     * @mbggenerated
     */
    public String getInstOrderNo() {
        return instOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.inst_order_no
     *
     * @param instOrderNo the value for tt_inst_order.inst_order_no
     *
     * @mbggenerated
     */
    public void setInstOrderNo(String instOrderNo) {
        this.instOrderNo = instOrderNo == null ? null : instOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.request_type
     *
     * @return the value of tt_inst_order.request_type
     *
     * @mbggenerated
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.request_type
     *
     * @param requestType the value for tt_inst_order.request_type
     *
     * @mbggenerated
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.fund_channel_code
     *
     * @return the value of tt_inst_order.fund_channel_code
     *
     * @mbggenerated
     */
    public String getFundChannelCode() {
        return fundChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.fund_channel_code
     *
     * @param fundChannelCode the value for tt_inst_order.fund_channel_code
     *
     * @mbggenerated
     */
    public void setFundChannelCode(String fundChannelCode) {
        this.fundChannelCode = fundChannelCode == null ? null : fundChannelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.fund_channel_api
     *
     * @return the value of tt_inst_order.fund_channel_api
     *
     * @mbggenerated
     */
    public String getFundChannelApi() {
        return fundChannelApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.fund_channel_api
     *
     * @param fundChannelApi the value for tt_inst_order.fund_channel_api
     *
     * @mbggenerated
     */
    public void setFundChannelApi(String fundChannelApi) {
        this.fundChannelApi = fundChannelApi == null ? null : fundChannelApi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.currency
     *
     * @return the value of tt_inst_order.currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.currency
     *
     * @param currency the value for tt_inst_order.currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.amount
     *
     * @return the value of tt_inst_order.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.amount
     *
     * @param amount the value for tt_inst_order.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.status
     *
     * @return the value of tt_inst_order.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.status
     *
     * @param status the value for tt_inst_order.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.communicate_type
     *
     * @return the value of tt_inst_order.communicate_type
     *
     * @mbggenerated
     */
    public String getCommunicateType() {
        return communicateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.communicate_type
     *
     * @param communicateType the value for tt_inst_order.communicate_type
     *
     * @mbggenerated
     */
    public void setCommunicateType(String communicateType) {
        this.communicateType = communicateType == null ? null : communicateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.communicate_status
     *
     * @return the value of tt_inst_order.communicate_status
     *
     * @mbggenerated
     */
    public String getCommunicateStatus() {
        return communicateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.communicate_status
     *
     * @param communicateStatus the value for tt_inst_order.communicate_status
     *
     * @mbggenerated
     */
    public void setCommunicateStatus(String communicateStatus) {
        this.communicateStatus = communicateStatus == null ? null : communicateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.flag
     *
     * @return the value of tt_inst_order.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.flag
     *
     * @param flag the value for tt_inst_order.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.gmt_submit
     *
     * @return the value of tt_inst_order.gmt_submit
     *
     * @mbggenerated
     */
    public Date getGmtSubmit() {
        return gmtSubmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.gmt_submit
     *
     * @param gmtSubmit the value for tt_inst_order.gmt_submit
     *
     * @mbggenerated
     */
    public void setGmtSubmit(Date gmtSubmit) {
        this.gmtSubmit = gmtSubmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.retry_times
     *
     * @return the value of tt_inst_order.retry_times
     *
     * @mbggenerated
     */
    public Integer getRetryTimes() {
        return retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.retry_times
     *
     * @param retryTimes the value for tt_inst_order.retry_times
     *
     * @mbggenerated
     */
    public void setRetryTimes(Integer retryTimes) {
        this.retryTimes = retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.gmt_next_retry
     *
     * @return the value of tt_inst_order.gmt_next_retry
     *
     * @mbggenerated
     */
    public String getGmtNextRetry() {
        return gmtNextRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.gmt_next_retry
     *
     * @param gmtNextRetry the value for tt_inst_order.gmt_next_retry
     *
     * @mbggenerated
     */
    public void setGmtNextRetry(String gmtNextRetry) {
        this.gmtNextRetry = gmtNextRetry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.gmt_create
     *
     * @return the value of tt_inst_order.gmt_create
     *
     * @mbggenerated
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.gmt_create
     *
     * @param gmtCreate the value for tt_inst_order.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.gmt_modified
     *
     * @return the value of tt_inst_order.gmt_modified
     *
     * @mbggenerated
     */
    public String getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.gmt_modified
     *
     * @param gmtModified the value for tt_inst_order.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(String gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.memo
     *
     * @return the value of tt_inst_order.memo
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.memo
     *
     * @param memo the value for tt_inst_order.memo
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.extension
     *
     * @return the value of tt_inst_order.extension
     *
     * @mbggenerated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.extension
     *
     * @param extension the value for tt_inst_order.extension
     *
     * @mbggenerated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.portion
     *
     * @return the value of tt_inst_order.portion
     *
     * @mbggenerated
     */
    public BigDecimal getPortion() {
        return portion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.portion
     *
     * @param portion the value for tt_inst_order.portion
     *
     * @mbggenerated
     */
    public void setPortion(BigDecimal portion) {
        this.portion = portion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.product_code
     *
     * @return the value of tt_inst_order.product_code
     *
     * @mbggenerated
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.product_code
     *
     * @param productCode the value for tt_inst_order.product_code
     *
     * @mbggenerated
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.gmt_booking_submit
     *
     * @return the value of tt_inst_order.gmt_booking_submit
     *
     * @mbggenerated
     */
    public Date getGmtBookingSubmit() {
        return gmtBookingSubmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.gmt_booking_submit
     *
     * @param gmtBookingSubmit the value for tt_inst_order.gmt_booking_submit
     *
     * @mbggenerated
     */
    public void setGmtBookingSubmit(Date gmtBookingSubmit) {
        this.gmtBookingSubmit = gmtBookingSubmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.payment_seq_no
     *
     * @return the value of tt_inst_order.payment_seq_no
     *
     * @mbggenerated
     */
    public String getPaymentSeqNo() {
        return paymentSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.payment_seq_no
     *
     * @param paymentSeqNo the value for tt_inst_order.payment_seq_no
     *
     * @mbggenerated
     */
    public void setPaymentSeqNo(String paymentSeqNo) {
        this.paymentSeqNo = paymentSeqNo == null ? null : paymentSeqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.inst_user_no
     *
     * @return the value of tt_inst_order.inst_user_no
     *
     * @mbggenerated
     */
    public String getInstUserNo() {
        return instUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.inst_user_no
     *
     * @param instUserNo the value for tt_inst_order.inst_user_no
     *
     * @mbggenerated
     */
    public void setInstUserNo(String instUserNo) {
        this.instUserNo = instUserNo == null ? null : instUserNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.biz_time
     *
     * @return the value of tt_inst_order.biz_time
     *
     * @mbggenerated
     */
    public Date getBizTime() {
        return bizTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.biz_time
     *
     * @param bizTime the value for tt_inst_order.biz_time
     *
     * @mbggenerated
     */
    public void setBizTime(Date bizTime) {
        this.bizTime = bizTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.channel_date
     *
     * @return the value of tt_inst_order.channel_date
     *
     * @mbggenerated
     */
    public Date getChannelDate() {
        return channelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.channel_date
     *
     * @param channelDate the value for tt_inst_order.channel_date
     *
     * @mbggenerated
     */
    public void setChannelDate(Date channelDate) {
        this.channelDate = channelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.biz_type
     *
     * @return the value of tt_inst_order.biz_type
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.biz_type
     *
     * @param bizType the value for tt_inst_order.biz_type
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.fund_date
     *
     * @return the value of tt_inst_order.fund_date
     *
     * @mbggenerated
     */
    public Date getFundDate() {
        return fundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.fund_date
     *
     * @param fundDate the value for tt_inst_order.fund_date
     *
     * @mbggenerated
     */
    public void setFundDate(Date fundDate) {
        this.fundDate = fundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_inst_order.pre_inst_order_no
     *
     * @return the value of tt_inst_order.pre_inst_order_no
     *
     * @mbggenerated
     */
    public String getPreInstOrderNo() {
        return preInstOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_inst_order.pre_inst_order_no
     *
     * @param preInstOrderNo the value for tt_inst_order.pre_inst_order_no
     *
     * @mbggenerated
     */
    public void setPreInstOrderNo(String preInstOrderNo) {
        this.preInstOrderNo = preInstOrderNo == null ? null : preInstOrderNo.trim();
    }
}