package com.snoweagle.console.dal.persistence;

import java.util.List;

import com.snoweagle.console.common.domain.order.OrderRequest;
import com.snoweagle.console.dal.domain.ControlOrder;

/**
 * @author n.tang
 *
 */
public interface ControlOrderMapper {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_inst_order_result
     * @param OrderRequest orderRequest
     * @return List<ControlOrder>
     */
    List<ControlOrder> selectByControlOrderParams(OrderRequest orderRequest);
}
