package com.snoweagle.console.dal.persistence;

import com.snoweagle.console.common.domain.order.OrderRequest;
import com.snoweagle.console.dal.domain.InstOrder;
import com.snoweagle.console.dal.domain.InstOrderResult;

import java.util.List;

public interface InstOrderMapper {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_inst_order
     * @param OrderRequest instOrderRequest
     * @return List<InstOrder>
     */
    List<InstOrder> selectByDynamicParams(OrderRequest orderRequest);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_inst_order_result
     * @param String instOrderNo
     * @return List<InstOrderResult>
     */
    List<InstOrderResult> selectByInstOrderNo(String instOrderNo);
    
}